.\alu-main\Adder\adder_8bit.v 
.\alu-main\Adder\cla_adder.v 
.\alu-main\Adder\comparator_2bit.v 
.\alu-main\Adder\comparator_32bit.v 
.\alu-main\Adder\comparator_8bit.v 
.\alu-main\Adder\full_adder.v 
.\alu-main\ALU_Interface\alu.v 
.\alu-main\ALU_Interface\alu_op.v 
.\alu-main\Logic\and32.v 
.\alu-main\Logic\mux_1.v 
.\alu-main\Logic\mux_32.v 
.\alu-main\Logic\not32.v 
.\alu-main\Logic\or32.v 
.\alu-main\Shifter\left_barrel_1.v 
.\alu-main\Shifter\left_barrel_16.v 
.\alu-main\Shifter\left_barrel_2.v 
.\alu-main\Shifter\left_barrel_4.v 
.\alu-main\Shifter\left_barrel_8.v 
.\alu-main\Shifter\right_barrel_1.v 
.\alu-main\Shifter\right_barrel_16.v 
.\alu-main\Shifter\right_barrel_2.v 
.\alu-main\Shifter\right_barrel_4.v 
.\alu-main\Shifter\right_barrel_8.v 
.\alu-main\Shifter\sll32.v 
.\alu-main\Shifter\sra32.v 
.\multdiv-main\memory\counter64.v 
.\multdiv-main\memory\register1.v 
.\multdiv-main\memory\register64.v 
.\multdiv-main\memory\register65.v 
.\multdiv-main\memory\tffe_ref.v 
.\multdiv-main\multdiv\div.v 
.\multdiv-main\multdiv\divControl.v 
.\multdiv-main\multdiv\mult.v 
.\multdiv-main\multdiv\multControl.v 
.\multdiv-main\multdiv\multdiv.v 
.\multdiv-main\multdiv\productSelector.v 
.\multdiv-main\multdiv\twosComp32.v 
.\processor-main\hazard-logic\bypassControl.v 
.\processor-main\hazard-logic\interlockDetector.v 
.\processor-main\logic\instructionType.v 
.\processor-main\logic\signExtension17to32.v 
.\processor-main\logic\signExtension27to32.v 
.\processor-main\processor\branchControl.v 
.\processor-main\processor\decodeControl.v 
.\processor-main\processor\executeControl.v 
.\processor-main\processor\fetchControl.v 
.\processor-main\processor\memoryControl.v 
.\processor-main\processor\PC.v 
.\processor-main\processor\processor.v 
.\processor-main\processor\RAM.v 
.\processor-main\processor\ROM.v 
.\processor-main\processor\Wrapper.v 
.\processor-main\processor\writebackControl.v 
.\regfile-main\Logic\buffer32.v 
.\regfile-main\Logic\decoder32.v 
.\regfile-main\regfile\dffe_ref.v 
.\regfile-main\regfile\regfile.v 
.\regfile-main\regfile\register32.v 
.\processor-main\Wrapper_tb.v 
